name: Build

inputs:
  os_name:
    description: A descriptive name for the operating system (e.g. linux, windows, web)
    required: true
  platform_name:
    description: A descriptive name for the target platform (e.g. amd64, aarch64, wasm)
    required: true
  publish:
    description: A boolean that enables publishing of artifacts
    required: true

runs:
  using: "composite"
  steps:
    - name: "Checkout repo"
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Linux Dependencies for SDL
      if: ${{ runner.os == 'Linux' && inputs.os_name != 'web' }}
      shell: bash
      # See Libraries/SDL/docs/README-linux.md
      run: >
        sudo apt-get update && 
        sudo apt-get install build-essential git make
        pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev
        libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev
        libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev
        libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev
        libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev
        libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev
      env:
        WLR_BACKENDS: headless
        WLR_LIBINPUT_NO_DEVICES: 1
        WAYLAND_DISPLAY: wayland-1
        GTK_USE_PORTAL: 0
    - name: Setup Emscripten
      if: ${{ inputs.os_name == 'web' }}
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: latest
        actions-cache-folder: 'emsdk-cache'
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.31.x'
    - name: "Prepare Project"
      shell: bash
      run: >
        if [ "${{ inputs.os_name }}" == "web" ]; then
          emcmake cmake -S ./ -B buildweb -DTACTILITY_BOARD=websimulator
        else
          cmake -S ./ -B buildsim
        fi
    - name: "Build Tests"
      shell: bash
      run: >
        if [ "${{ inputs.os_name }}" == "web" ]; then
          emmake cmake --build buildweb --target WebSimulator
        else
          cmake --build buildsim --target FirmwareSim
        fi
    - name: 'Release'
      shell: bash
      run: >
        if [ "${{ inputs.os_name }}" == "web" ]; then
          Buildscripts/release-simulator.sh buildweb release/WebSimulator-${{ inputs.os_name }}-${{ inputs.platform_name }}
        else
          Buildscripts/release-simulator.sh buildsim release/Simulator-${{ inputs.os_name }}-${{ inputs.platform_name }}
        fi
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      if: ${{ inputs.publish == 'true' }}
      with:
        name: Simulator-${{ inputs.os_name }}-${{ inputs.platform_name }}
        path: release/Simulator-${{ inputs.os_name }}-${{ inputs.platform_name }}
        retention-days: 30
